apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redmine
  namespace: default
spec:
  sources:
  - repoURL: https://charts.bitnami.com/bitnami
    chart: redmine
    targetRevision: 25.0.1
    helm:
      valueFiles:
        - $values/03_REDMINE/values.yaml
  - repoURL: 'https://github.com/davidgoncalvesz/deployment-exercises-Tiebevn.git'
    targetRevision: main
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
